workflows:

  flutter-ios-simulator:

    name: Flutter iOS Simulator

    environment:

      flutter: 3.27.3

      xcode: 16.2

    scripts:

      - name: install dependencies

        script: flutter pub get

      - name: Build unsigned .app

        script: |  

          xcodebuild -workspace "ios/Runner.xcworkspace" \

            -scheme "Runner" \

            -sdk iphonesimulator \

            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \

            -configuration Debug \

            CODE_SIGN_IDENTITY="" \

            CODE_SIGNING_REQUIRED=NO \

            CODE_SIGNING_ALLOWED=NO \

            -derivedDataPath ios/output

    artifacts:

      - ios/output/Build/Products/Debug-iphonesimulator/Runner.app